# Generated by Django 5.2.11 on 2026-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contentpackage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_student_visible',
            field=models.BooleanField(default=True),
        ),
    ]
