# Generated by Django 5.2.11 on 2026-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_is_student_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='is_student_visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
