# Generated by Django 5.2.11 on 2026-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_registration', '0007_lead_stream_studentprofile_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='study_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
